"""empty message

Revision ID: 0823ce261fca
Revises: 739126ff904f
Create Date: 2023-01-06 19:52:36.645268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '0823ce261fca'
down_revision = '739126ff904f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commentflags', 'resolution_notif_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('flags', 'resolution_notif_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flags', 'resolution_notif_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('commentflags', 'resolution_notif_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
