"""empty message

Revision ID: 085aebc76b76
Revises: 14e8dcab2bb8
Create Date: 2022-10-21 14:54:34.220653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '085aebc76b76'
down_revision = '14e8dcab2bb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'upvotes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'downvotes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_domains_domain'), 'domains', ['domain'], unique=False)
    op.alter_column('submissions', 'upvotes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submissions', 'downvotes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'downvotes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('submissions', 'upvotes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_domains_domain'), table_name='domains')
    op.alter_column('comments', 'downvotes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'upvotes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
