"""empty message

Revision ID: 0bb67dcceca2
Revises: 1fed9fd89935
Create Date: 2022-11-30 18:45:30.791979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '0bb67dcceca2'
down_revision = '1fed9fd89935'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('users_created_utc_idx', 'users', ['created_utc'], unique=False, postgresql_using='btree', postgresql_ops={'created_utc': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('users_created_utc_idx', table_name='users', postgresql_using='btree', postgresql_ops={'created_utc': 'DESC'})
    # ### end Alembic commands ###
