"""empty message

Revision ID: 0be87d370442
Revises: f09fb6e80505
Create Date: 2023-03-30 17:26:33.169060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '0be87d370442'
down_revision = 'f09fb6e80505'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('per_page_preference', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'per_page_preference')
    # ### end Alembic commands ###
