"""empty message

Revision ID: 1fed9fd89935
Revises: bbdb4a8630d7
Create Date: 2022-11-30 18:39:24.923319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '1fed9fd89935'
down_revision = 'bbdb4a8630d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_parent_submission'), 'comments', ['parent_submission'], unique=False)
    op.create_index(op.f('ix_notifications_comment_id'), 'notifications', ['comment_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_comment_id'), table_name='notifications')
    op.drop_index(op.f('ix_comments_parent_submission'), table_name='comments')
    # ### end Alembic commands ###
