"""empty message

Revision ID: 2cc1b407a842
Revises: 3cca489dc0f5
Create Date: 2022-12-15 19:47:44.693752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '2cc1b407a842'
down_revision = '3cca489dc0f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('users_email_trgm_idx', 'users', ['email'], unique=False, postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops'})
    op.drop_column('users', 'tos_agreed_utc')
    op.drop_column('users', 'feed_nonce')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('feed_nonce', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tos_agreed_utc', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('users_email_trgm_idx', table_name='users', postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops'})
    # ### end Alembic commands ###
