"""empty message

Revision ID: 381b6bbf7607
Revises: db852fa22c9b
Create Date: 2022-10-28 23:13:15.370586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '381b6bbf7607'
down_revision = 'db852fa22c9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'css',
               existing_type=sa.VARCHAR(length=65536),
               nullable=False)
    op.drop_column('boards', 'secondary_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('secondary_color', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.alter_column('boards', 'css',
               existing_type=sa.VARCHAR(length=65536),
               nullable=True)
    # ### end Alembic commands ###
