"""empty message

Revision ID: 3cca489dc0f5
Revises: 79938fd97415
Create Date: 2022-12-12 14:58:41.896491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '3cca489dc0f5'
down_revision = '79938fd97415'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_aux_id'), 'comments_aux', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_aux_id'), 'submissions_aux', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_aux_id'), table_name='submissions_aux')
    op.drop_index(op.f('ix_comments_aux_id'), table_name='comments_aux')
    # ### end Alembic commands ###
