"""empty message

Revision ID: 62b2a7f1d7cc
Revises: 381b6bbf7607
Create Date: 2022-11-08 21:52:53.866281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '62b2a7f1d7cc'
down_revision = '381b6bbf7607'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useragents', sa.Column('instaban', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useragents', 'instaban')
    # ### end Alembic commands ###
