"""empty message

Revision ID: 739126ff904f
Revises: 2cc1b407a842
Create Date: 2023-01-06 19:45:43.512712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '739126ff904f'
down_revision = '2cc1b407a842'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commentflags', sa.Column('resolution_notif_sent', sa.Boolean(), nullable=True))
    op.add_column('flags', sa.Column('resolution_notif_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flags', 'resolution_notif_sent')
    op.drop_column('commentflags', 'resolution_notif_sent')
    # ### end Alembic commands ###
