"""empty message

Revision ID: 79938fd97415
Revises: 8328d5cb4e97
Create Date: 2022-12-12 12:33:57.312930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '79938fd97415'
down_revision = '8328d5cb4e97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_follows_target_id'), 'follows', ['target_id'], unique=False)
    op.create_index(op.f('ix_follows_user_id'), 'follows', ['user_id'], unique=False)
    op.create_index(op.f('ix_modactions_board_id'), 'modactions', ['board_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_board_id'), 'subscriptions', ['board_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_userblocks_target_id'), 'userblocks', ['target_id'], unique=False)
    op.create_index(op.f('ix_userblocks_user_id'), 'userblocks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userblocks_user_id'), table_name='userblocks')
    op.drop_index(op.f('ix_userblocks_target_id'), table_name='userblocks')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_board_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_modactions_board_id'), table_name='modactions')
    op.drop_index(op.f('ix_follows_user_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_target_id'), table_name='follows')
    # ### end Alembic commands ###
