"""empty message

Revision ID: 7a6f57f52371
Revises: 9d4bc44adcef
Create Date: 2022-10-19 08:44:42.450913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '7a6f57f52371'
down_revision = '9d4bc44adcef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbans')
    op.add_column('boards', sa.Column('subcat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'subcat_id')
    op.create_table('chatbans',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_utc', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('banning_mod_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['banning_mod_id'], ['users.id'], name='chatbans_banning_mod_id_fkey'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name='chatbans_board_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chatbans_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chatbans_pkey')
    )
    # ### end Alembic commands ###
