"""empty message

Revision ID: 8bb51e6ec1eb
Revises: 9d3a0e7492cd
Create Date: 2022-11-26 22:30:02.355939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '8bb51e6ec1eb'
down_revision = '9d3a0e7492cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('is_locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'is_locked')
    # ### end Alembic commands ###
