"""empty message

Revision ID: 9d3a0e7492cd
Revises: 62b2a7f1d7cc
Create Date: 2022-11-08 22:07:06.429966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = '9d3a0e7492cd'
down_revision = '62b2a7f1d7cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ips_addr', table_name='ips')
    op.create_index(op.f('ix_ips_addr'), 'ips', ['addr'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ips_addr'), table_name='ips')
    op.create_index('ix_ips_addr', 'ips', ['addr'], unique=False)
    # ### end Alembic commands ###
