"""empty message

Revision ID: a1aa1b7626b6
Revises: f3552bdef258
Create Date: 2022-10-26 18:35:29.023440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = 'a1aa1b7626b6'
down_revision = 'f3552bdef258'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('domains', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('domains', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
