"""empty message

Revision ID: bbdb4a8630d7
Revises: 8bb51e6ec1eb
Create Date: 2022-11-30 18:32:10.657874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = 'bbdb4a8630d7'
down_revision = '8bb51e6ec1eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('boards_rank_trending_idx', 'boards', ['rank_trending'], unique=False, postgresql_using='btree', postgresql_ops={'rank_trending': 'DESC'})
    op.create_index('boards_stored_subscriber_idx', 'boards', ['stored_subscriber_count'], unique=False, postgresql_using='btree', postgresql_ops={'stored_subscriber_count': 'DESC'})
    op.create_index('comments_created_utc_desc_idx', 'comments', ['created_utc'], unique=False, postgresql_using='btree', postgresql_ops={'created_utc': 'DESC'})
    op.create_index('comments_score_disputed_desc_idx', 'comments', ['score_disputed'], unique=False, postgresql_using='btree', postgresql_ops={'score_disputed': 'DESC'})
    op.create_index('comments_score_hot_desc_idx', 'comments', ['score_hot'], unique=False, postgresql_using='btree', postgresql_ops={'score_hot': 'DESC'})
    op.create_index('comments_score_top_desc_idx', 'comments', ['score_top'], unique=False, postgresql_using='btree', postgresql_ops={'score_top': 'DESC'})
    op.create_index('submissions_created_utc_desc_idx', 'submissions', ['created_utc'], unique=False, postgresql_using='btree', postgresql_ops={'created_utc': 'DESC'})
    op.create_index('submissions_score_activity_desc_idx', 'submissions', ['score_activity'], unique=False, postgresql_using='btree', postgresql_ops={'score_activity': 'DESC'})
    op.create_index('submissions_score_disputed_desc_idx', 'submissions', ['score_disputed'], unique=False, postgresql_using='btree', postgresql_ops={'score_disputed': 'DESC'})
    op.create_index('submissions_score_hot_desc_idx', 'submissions', ['score_hot'], unique=False, postgresql_using='btree', postgresql_ops={'score_hot': 'DESC'})
    op.create_index('submissions_score_top_desc_idx', 'submissions', ['score_top'], unique=False, postgresql_using='btree', postgresql_ops={'score_top': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('submissions_score_top_desc_idx', table_name='submissions', postgresql_using='btree', postgresql_ops={'score_top': 'DESC'})
    op.drop_index('submissions_score_hot_desc_idx', table_name='submissions', postgresql_using='btree', postgresql_ops={'score_hot': 'DESC'})
    op.drop_index('submissions_score_disputed_desc_idx', table_name='submissions', postgresql_using='btree', postgresql_ops={'score_disputed': 'DESC'})
    op.drop_index('submissions_score_activity_desc_idx', table_name='submissions', postgresql_using='btree', postgresql_ops={'score_activity': 'DESC'})
    op.drop_index('submissions_created_utc_desc_idx', table_name='submissions', postgresql_using='btree', postgresql_ops={'created_utc': 'DESC'})
    op.drop_index('comments_score_top_desc_idx', table_name='comments', postgresql_using='btree', postgresql_ops={'score_top': 'DESC'})
    op.drop_index('comments_score_hot_desc_idx', table_name='comments', postgresql_using='btree', postgresql_ops={'score_hot': 'DESC'})
    op.drop_index('comments_score_disputed_desc_idx', table_name='comments', postgresql_using='btree', postgresql_ops={'score_disputed': 'DESC'})
    op.drop_index('comments_created_utc_desc_idx', table_name='comments', postgresql_using='btree', postgresql_ops={'created_utc': 'DESC'})
    op.drop_index('boards_stored_subscriber_idx', table_name='boards', postgresql_using='btree', postgresql_ops={'stored_subscriber_count': 'DESC'})
    op.drop_index('boards_rank_trending_idx', table_name='boards', postgresql_using='btree', postgresql_ops={'rank_trending': 'DESC'})
    # ### end Alembic commands ###
