"""empty message

Revision ID: c6e794e68f8d
Revises: fd9a1778c3f6
Create Date: 2022-10-24 19:43:09.148634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = 'c6e794e68f8d'
down_revision = 'fd9a1778c3f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ips', sa.Column('unban_utc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ips', 'unban_utc')
    # ### end Alembic commands ###
