"""empty message

Revision ID: db852fa22c9b
Revises: a1aa1b7626b6
Create Date: 2022-10-27 21:20:00.573181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = 'db852fa22c9b'
down_revision = 'a1aa1b7626b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'color_nonce')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('color_nonce', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
