"""empty message

Revision ID: f09fb6e80505
Revises: a6962181aaf1
Create Date: 2023-02-09 11:38:22.587018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = 'f09fb6e80505'
down_revision = 'a6962181aaf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_aux_id', table_name='comments_aux')
    op.create_index(op.f('ix_comments_aux_id'), 'comments_aux', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_aux_id'), table_name='comments_aux')
    op.create_index('ix_comments_aux_id', 'comments_aux', ['id'], unique=False)
    # ### end Alembic commands ###
