"""empty message

Revision ID: f3552bdef258
Revises: c6e794e68f8d
Create Date: 2022-10-26 18:20:37.338289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = 'f3552bdef258'
down_revision = 'c6e794e68f8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('is_banned', sa.Boolean(), nullable=True))
    op.drop_column('domains', 'can_submit')
    op.drop_column('domains', 'can_comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('can_comment', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('domains', sa.Column('can_submit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('domains', 'is_banned')
    # ### end Alembic commands ###
