"""empty message

Revision ID: fd9a1778c3f6
Revises: 085aebc76b76
Create Date: 2022-10-21 18:28:55.137592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue


# revision identifiers, used by Alembic.
revision = 'fd9a1778c3f6'
down_revision = '085aebc76b76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'stored_subscriber_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'stored_subscriber_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
